In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("nba.csv")
print(df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]

In [9]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [10]:
df["Team"]

0      Boston Celtics
1      Boston Celtics
2      Boston Celtics
3      Boston Celtics
4      Boston Celtics
            ...
453         Utah Jazz
454         Utah Jazz
455         Utah Jazz
456         Utah Jazz
457               NaN
Name: Team, Length: 458, dtype: object

In [15]:
df1=df[["Name","Salary"]]
df1

              Name     Salary
0    Avery Bradley  7730337.0
1      Jae Crowder  6796117.0
2     John Holland        NaN
3      R.J. Hunter  1148640.0
4    Jonas Jerebko  5000000.0
..             ...        ...
453   Shelvin Mack  2433333.0
454      Raul Neto   900000.0
455   Tibor Pleiss  2900000.0
456    Jeff Withey   947276.0
457            NaN        NaN

[458 rows x 2 columns]

In [16]:
df1=df["Experience"]=2
df.head

<bound method NDFrame.head of               Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary  Experience
0                Texas  7730337.0           2
1            Marquette  6796117.0           2
2    Boston University        NaN           2
3        Georgia State  1148640.0           2
4                  NaN  5000000.0           2
..                 ...        ...         ...
453             Butler  2433333.0           2
454                NaN   900000.0           2
455                NaN  2900000.0           2
456             Kansas   947276.0           2
457                NaN        NaN           2

[458 rows x 10 columns]>

In [17]:
df["Salary_after_bonus"] = df["Salary"] * 1.10
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0
...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2,2676666.3
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,2,990000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,2,3190000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,2,1042003.6
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN

In [18]:
df2=df.drop("Experience",axis=1)
df2

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5500000.0
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2676666.3
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,990000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,3190000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,1042003.6
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df3=df2.drop("Salary_after_bonus",axis=1)
df3

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
new_row = {
    "Name" : "Emma",
    "Team" : "Boston Celtics",
    "Number":99.0,
    "Position":"SG",
    "Age":25,
    "Height":"6-10",
    "weight":231.0,
    "College":"Butler",
    "Salary":9000000
}
new_df = pd.DataFrame([new_row])
print(new_df)
print("************************")
print()
df4=pd.concat([df3, new_df], ignore_index=True)
print(df4)

   Name            Team  Number Position  Age Height  weight College   Salary
0  Emma  Boston Celtics    99.0       SG   25   6-10   231.0  Butler  9000000
************************

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN
458           Emma  Boston Celtics    99.0       SG  25.0   6-10     NaN

               College     Salary  weight
0                Texas  7730337.0     NaN
1            Marquette  6796117.0     NaN
2    Boston University        NaN     NaN
3        Georgia State  1148640.0     NaN
4                  NaN  5000000.0     NaN
..                 ...        ...     ...
454                NaN   900000.0     NaN
455                NaN  2900000.0     NaN
456             Kansas   947276.0     NaN
457                NaN        NaN     NaN
458             Butler  9000000.0   231.0

[459 rows x 10 columns]

In [23]:
df4.drop(457, inplace=True)
print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
458           Emma  Boston Celtics    99.0       SG  25.0   6-10     NaN

               College     Salary  weight
0                Texas  7730337.0     NaN
1            Marquette  6796117.0     NaN
2    Boston University        NaN     NaN
3        Georgia State  1148640.0     NaN
4                  NaN  5000000.0     NaN
..                 ...        ...     ...
453             Butler  2433333.0     NaN
454                NaN   900000.0     NaN
455                NaN  2900000.0     NaN
456             Kansas   947276.0     NaN
458             Butler  9000000.0   231.0

[458 rows x 10 columns]

In [24]:
df4.drop(1, inplace=True)
print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
458           Emma  Boston Celtics    99.0       SG  25.0   6-10     NaN

               College      Salary  weight
0                Texas   7730337.0     NaN
2    Boston University         NaN     NaN
3        Georgia State   1148640.0     NaN
4                  NaN   5000000.0     NaN
5                  NaN  12000000.0     NaN
..                 ...         ...     ...
453             Butler   2433333.0     NaN
454                NaN    900000.0     NaN
455                NaN   2900000.0     NaN
456             Kansas    947276.0     NaN
458             Butler   9000000.0   231.0

[457 rows x 10 columns]

In [25]:
df4.reset_index(drop=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,weight
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,NaN
1,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
2,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,NaN
3,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,NaN
4,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,NaN
...,...,...,...,...,...,...,...,...,...,...
452,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,NaN
453,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,NaN
454,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,NaN
455,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,NaN
456,Emma,Boston Celtics,99.0,SG,25.0,6-10,NaN,Butler,9000000.0,231.0

## Loc and iloc

In [27]:
data= {
    "Name" : ["Alice","Bob","Charlie","David","Emma"],
    "Age" : [22,56,23,45,28],
    "Department":["HR","IT","Finance","IT","Marketing"],
    "Salary":[40000,50000,20000,450000,1000000]
}
df=pd.DataFrame(data)
df

      Name  Age Department   Salary
0    Alice   22         HR    40000
1      Bob   56         IT    50000
2  Charlie   23    Finance    20000
3    David   45         IT   450000
4     Emma   28  Marketing  1000000

In [28]:
df.loc[[2]]

      Name  Age Department  Salary
2  Charlie   23    Finance   20000

In [29]:
df.loc[[1,3]]

    Name  Age Department  Salary
1    Bob   56         IT   50000
3  David   45         IT  450000

In [30]:
df.loc[2,"Name"]

'Charlie'

In [31]:
df.loc[[1,3],["Name","Department"]]

    Name Department
1    Bob         IT
3  David         IT

In [32]:
df.loc[1:3]

      Name  Age Department  Salary
1      Bob   56         IT   50000
2  Charlie   23    Finance   20000
3    David   45         IT  450000

In [33]:
df.loc[df["Salary"] > 50000]

    Name  Age Department   Salary
3  David   45         IT   450000
4   Emma   28  Marketing  1000000

In [34]:
df.loc[df["Salary"] >50000, ["Name","Salary"]]

    Name   Salary
3  David   450000
4   Emma  1000000

In [35]:
df.loc[2,"Salary"] = 1234567
df

      Name  Age Department   Salary
0    Alice   22         HR    40000
1      Bob   56         IT    50000
2  Charlie   23    Finance  1234567
3    David   45         IT   450000
4     Emma   28  Marketing  1000000

In [37]:
data = {
     "Name" : ["Alice","Bob","Charlie","David","Emma"],
    "Age" : [22,56,23,45,28],
    "Department":["HR","IT","Finance","IT","Marketing"],
    "Salary":[40000,50000,750000,550000,6900000]
}
df = pd.DataFrame(data,index=(1,2,3,4,5))
print(df)

      Name  Age Department   Salary
1    Alice   22         HR    40000
2      Bob   56         IT    50000
3  Charlie   23    Finance   750000
4    David   45         IT   550000
5     Emma   28  Marketing  6900000

In [43]:
data = {
     "Name" : ["Alice","Bob","Charlie","David","Emma"],
    "Age" : [22,56,23,45,28],
    "Department":["HR","IT","Finance","IT","Marketing"],
    "Salary":[40000,50000,750000,550000,6900000]
}
# df = pd.DataFrame(data,index=("A","B","C","D","E"))
df = pd.DataFrame(data,index=[x for x in "abcde"])
print(df)

      Name  Age Department   Salary
a    Alice   22         HR    40000
b      Bob   56         IT    50000
c  Charlie   23    Finance   750000
d    David   45         IT   550000
e     Emma   28  Marketing  6900000

In [44]:
df.loc["a"]

Name          Alice
Age              22
Department       HR
Salary        40000
Name: a, dtype: object

In [41]:
df.iloc[1]

Name            Bob
Age              56
Department       IT
Salary        50000
Name: B, dtype: object

In [46]:
df.loc["a":"d"]

      Name  Age Department  Salary
a    Alice   22         HR   40000
b      Bob   56         IT   50000
c  Charlie   23    Finance  750000
d    David   45         IT  550000

In [48]:
df.iloc[0:4]

      Name  Age Department  Salary
a    Alice   22         HR   40000
b      Bob   56         IT   50000
c  Charlie   23    Finance  750000
d    David   45         IT  550000

In [50]:
df.iloc[2]

Name          Charlie
Age                23
Department    Finance
Salary         750000
Name: c, dtype: object

In [52]:
df.iloc[[1,3]]

    Name  Age Department  Salary
b    Bob   56         IT   50000
d  David   45         IT  550000

In [53]:
df.iloc[1,1]

np.int64(56)

In [55]:
df.iloc[1,[1,3]]

Age          56
Salary    50000
Name: b, dtype: object

In [56]:
df.iloc[:,1:3]

   Age Department
a   22         HR
b   56         IT
c   23    Finance
d   45         IT
e   28  Marketing

In [57]:
df.iloc[:,1]

a    22
b    56
c    23
d    45
e    28
Name: Age, dtype: int64