## DATA LOADING & OVERVIEW

## Question 1: Load the dataset.

In [3]:
import pandas as pd
df=pd.read_csv("google.csv")
print(df)

                                                     App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN
3                                  Sketch - Draw & Paint       ART_AND_DESIGN
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a Maroc - FR               FAMILY
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY
10838                             Parkinson Exercices FR              MEDICAL
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0
1         3.9     967                 14M     500,000+  Free     0
2         4.7   87510                8.7M   5,000,000+  Free     0
3         4.5  215644                 25M  50,000,000+  Free     0
4         4.3     967                2.8M     100,000+  Free     0
...       ...     ...                 ...          ...   ...   ...
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018
1           Everyone  Art & Design;Pretend Play  January 15, 2018
2           Everyone               Art & Design    August 1, 2018
3               Teen               Art & Design      June 8, 2018
4           Everyone    Art & Design;Creativity     June 20, 2018
...              ...                        ...               ...
10836       Everyone                  Education     July 25, 2017
10837       Everyone                  Education      July 6, 2018
10838       Everyone                    Medical  January 20, 2017
10839     Mature 17+          Books & Reference  January 19, 2015
10840       Everyone                  Lifestyle     July 25, 2018

              Current Ver         Android Ver
0                   1.0.0        4.0.3 and up
1                   2.0.0        4.0.3 and up
2                   1.2.4        4.0.3 and up
3      Varies with device          4.2 and up
4                     1.1          4.4 and up
...                   ...                 ...
10836                1.48          4.1 and up
10837                 1.0          4.1 and up
10838                 1.0          2.2 and up
10839  Varies with device  Varies with device
10840  Varies with device  Varies with device

[10841 rows x 13 columns]

## Question 2: Display the first 5 rows.

In [4]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

## Question 3: Display the last 5 rows.

In [5]:
print(df.tail())

                                                 App             Category  \
10836                               Sya9a Maroc - FR               FAMILY
10837               Fr. Mike Schmitz Audio Teachings               FAMILY
10838                         Parkinson Exercices FR              MEDICAL
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating             Genres      Last Updated         Current Ver  \
10836       Everyone          Education     July 25, 2017                1.48
10837       Everyone          Education      July 6, 2018                 1.0
10838       Everyone            Medical  January 20, 2017                 1.0
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device
10840       Everyone          Lifestyle     July 25, 2018  Varies with device

              Android Ver
10836          4.1 and up
10837          4.1 and up
10838          2.2 and up
10839  Varies with device
10840  Varies with device

### 4. Check dataset structure and non-null counts

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

### 5. Generate summary statistics for all columns

In [8]:
print(df.describe(include="all"))

           App Category       Rating Reviews                Size    Installs  \
count    10841    10841  9367.000000   10841               10841       10841
unique    9660       34          NaN    6002                 462          22
top     ROBLOX   FAMILY          NaN       0  Varies with device  1,000,000+
freq         9     1972          NaN     596                1695        1579
mean       NaN      NaN     4.193338     NaN                 NaN         NaN
std        NaN      NaN     0.537431     NaN                 NaN         NaN
min        NaN      NaN     1.000000     NaN                 NaN         NaN
25%        NaN      NaN     4.000000     NaN                 NaN         NaN
50%        NaN      NaN     4.300000     NaN                 NaN         NaN
75%        NaN      NaN     4.500000     NaN                 NaN         NaN
max        NaN      NaN    19.000000     NaN                 NaN         NaN

         Type  Price Content Rating Genres    Last Updated  \
count   10840  10841          10840  10841           10841
unique      3     93              6    120            1378
top      Free      0       Everyone  Tools  August 3, 2018
freq    10039  10040           8714    842             326
mean      NaN    NaN            NaN    NaN             NaN
std       NaN    NaN            NaN    NaN             NaN
min       NaN    NaN            NaN    NaN             NaN
25%       NaN    NaN            NaN    NaN             NaN
50%       NaN    NaN            NaN    NaN             NaN
75%       NaN    NaN            NaN    NaN             NaN
max       NaN    NaN            NaN    NaN             NaN

               Current Ver Android Ver
count                10833       10838
unique                2832          33
top     Varies with device  4.1 and up
freq                  1459        2451
mean                   NaN         NaN
std                    NaN         NaN
min                    NaN         NaN
25%                    NaN         NaN
50%                    NaN         NaN
75%                    NaN         NaN
max                    NaN         NaN

### 6. Display all column names and their data types

In [9]:
print(df.dtypes)

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

## DATA CLEANING (REAL-WORLD SCENARIOS)

### 7. Identify missing values in each column

In [10]:
print(df.isnull().sum())

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

### 8. Remove rows where "Rating" is missing

In [11]:
df = df.dropna(subset=["Rating"])

### 9. Fill missing values in "Type" with the most frequent value (mode)

In [12]:
df["Type"] = df["Type"].fillna(df["Type"].mode()[0])

### 10. Remove duplicate records from the dataset

In [13]:
df = df.drop_duplicates()

### 11. Clean "Installs" (remove '+', ',' and non-numeric entries if present, convert to int)

In [14]:
df["Installs"] = (
    df["Installs"]
    .astype(str)
    .str.replace("+", "", regex=False)
    .str.replace(",", "", regex=False)
)

### 12. Clean "Price" (remove '$' and convert to float)

In [15]:
df["Installs"] = (
    df["Installs"]
    .astype(str)
    .str.replace("+", "", regex=False)
    .str.replace(",", "", regex=False)
)

### 13. Convert "Reviews" column to integer type

In [ ]:
df["Reviews"] = df["Reviews"].astype(int)

### 14. Convert "Last Updated" column to datetime format

In [52]:
df['Last Updated'] = pd.to_datetime(
    df['Last Updated'],
    errors='coerce'
)
print(df['Last Updated'].dtype)

datetime64[ns]

##  STRING OPERATIONS

### 15. Convert all app names to lowercase

In [19]:
df["App"] = df["App"].str.lower()

### 16. Convert category names to uppercase

In [20]:
df["Category"] = df["Category"].str.upper()

### 17. Split the "Genres" column into multiple parts (takes the first genre)

In [21]:
df["Primary_Genre"] = df["Genres"].str.split(";").str[0]

### 18. Replace unwanted text patterns in "Category" (e.g., replacing underscores with spaces)

In [22]:
df["Category"] = df["Category"].str.replace("_", " ")

In [23]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,Art & Design
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,Art & Design
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,Art & Design
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,Art & Design
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,Art & Design
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,fr calculator,FAMILY,4.0,7,2.6M,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up,Education
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,Education
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,Education
10839,the scp foundation db fr nn5n,BOOKS AND REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,Books & Reference
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,Lifestyle

## FILTERING & SELECTION

### 19. Filter apps with rating greater than 4.5

In [24]:
high_rated = df[df["Rating"] > 4.5]

### 20. Find all free apps

In [25]:
free_apps = df[df["Price"] == 0]

### 21. Filter apps with installs greater than 1,000,000

In [54]:
df["Installs"] = pd.to_numeric(df["Installs"])

ValueError: Unable to parse string "Free" at position 8644

### 22. Select apps belonging to multiple categories

In [28]:
target_categories = ["GAME", "FAMILY", "TOOLS"]
selected_categories = df[df["Category"].isin(target_categories)]

### 23. Perform filtering using query syntax

In [29]:
query_filtered = df.query("Rating > 4.0 and Price == 0")

## 5. FEATURE ENGINEERING

### 24. Create a new column "Revenue" using installs and price

In [55]:
df["Revenue"] = df["Installs"] * df["Price"]

TypeError: can't multiply sequence by non-int of type 'str'

### 25. Categorize apps into rating groups (Low, Medium, High)

In [31]:
df["Rating_Group"] = pd.cut(
    df["Rating"], bins=[0, 3.0, 4.2, 5.0], labels=["Low", "Medium", "High"]
)

### 26. Create a new column to flag high-install apps (>1M installs)

In [57]:
df["Is_High_Install"] = df["Installs"].apply(lambda x: 1 if x > 1000000 else 0)

TypeError: '>' not supported between instances of 'str' and 'int'

### 27. Convert "Type" column into numeric values (Free=0, Paid=1)

In [33]:
df["Type_Numeric"] = df["Type"].map({"Free": 0, "Paid": 1})

In [34]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre,Rating_Group,Type_Numeric
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,Art & Design,Medium,0.0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,Art & Design,Medium,0.0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,Art & Design,High,0.0
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,Art & Design,High,0.0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,Art & Design,High,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,fr calculator,FAMILY,4.0,7,2.6M,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up,Education,Medium,0.0
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,Education,High,0.0
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,Education,High,0.0
10839,the scp foundation db fr nn5n,BOOKS AND REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,Books & Reference,High,0.0
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,Lifestyle,High,0.0

## SORTING & RANKING

### 28. Sort apps by number of installs in descending order

In [58]:
df.sort_values('Installs',ascending=False)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre,Rating_Group,Type_Numeric,Rating_Rank
10472,life made wi-fi touchscreen photo frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",NaT,4.0 and up,NaN,"February 11, 2018",NaN,NaN,1.0
4147,gboard - the google keyboard,TOOLS,4.2,1855262,Varies with device,500000000,Free,0,Everyone,Tools,2018-07-31,Varies with device,Varies with device,Tools,Medium,0.0,4865.0
371,google duo - high quality video calls,COMMUNICATION,4.6,2083237,Varies with device,500000000,Free,0,Everyone,Communication,2018-07-31,37.1.206017801.DR37_RC14,4.4 and up,Communication,High,0.0,1072.0
1661,temple run 2,GAME,4.3,8118609,62M,500000000,Free,0,Everyone,Action,2018-07-05,1.49.1,4.0 and up,Action,High,0.0,3849.0
3870,snapchat,SOCIAL,4.0,17000166,Varies with device,500000000,Free,0,Teen,Social,2018-07-30,Varies with device,Varies with device,Social,Medium,0.0,6410.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6046,best browser bd social networking,COMMUNICATION,4.8,6,21M,10,Free,0,Everyone,Communication,2018-07-04,2.0,4.1 and up,Communication,High,0.0,360.0
8526,dl image manager,PRODUCTIVITY,5.0,2,1.7M,10,Paid,$0.99,Everyone,Productivity,2018-07-29,1.0.5,4.0 and up,Productivity,High,1.0,2.0
5917,ra ga ba,GAME,5.0,2,20M,1,Paid,$1.49,Everyone,Arcade,2017-02-08,1.0.4,2.3 and up,Arcade,High,1.0,2.0
10697,mu.f.o.,GAME,5.0,2,16M,1,Paid,$0.99,Everyone,Arcade,2017-03-03,1.0,2.3 and up,Arcade,High,1.0,2.0
2454,kba-ez health guide,MEDICAL,5.0,4,25M,1,Free,0,Everyone,Medical,2018-08-02,1.0.72,4.0.3 and up,Medical,High,0.0,2.0

In [36]:
### 29. Identify top 10 apps based on number of reviews

In [59]:
df['Reviews']=pd.to_numeric(df['Reviews'], errors='coerce')
df.nlargest(10,'Reviews')[['App','Rating','Reviews']]

                                           App  Rating     Reviews
2544                                  facebook     4.1  78158306.0
3943                                  facebook     4.1  78128208.0
336                         whatsapp messenger     4.4  69119316.0
3904                        whatsapp messenger     4.4  69109672.0
2604                                 instagram     4.5  66577446.0
2545                                 instagram     4.5  66577313.0
3909                                 instagram     4.5  66509917.0
382   messenger – text and video chat for free     4.0  56646578.0
335   messenger – text and video chat for free     4.0  56642847.0
1879                            clash of clans     4.6  44893888.0

### 30. Identify bottom 10 apps based on installs

In [60]:
df['Installs']=pd.to_numeric(df['Installs'], errors='coerce')
df.nsmallest(10,'Installs')[['App','Rating','Installs']]

                                                   App  Rating  Installs
2454                               kba-ez health guide     5.0       1.0
5917                                          ra ga ba     5.0       1.0
10697                                          mu.f.o.     5.0       1.0
2450                                   tablet reminder     5.0       5.0
2459   anatomy & physiology vocabulary exam review app     5.0       5.0
2484                                 clinic doctor ehr     5.0       5.0
6700                                  brick breaker br     5.0       5.0
7147                                         cb heroes     5.0       5.0
7731                                           cq espm     5.0       5.0
8146                                           cz-help     5.0       5.0

### 31. Rank apps based on rating

In [40]:
df["Rating_Rank"] = df["Rating"].rank(ascending=False, method="min")

## GROUPBY & AGGREGATION

### 32. Calculate average rating for each category

In [41]:
avg_rating_per_cat = df.groupby("Category")["Rating"].mean()

### 33. Calculate total installs for each category

In [42]:
total_installs_per_cat = df.groupby("Category")["Installs"].sum()

### 34. Count the number of apps in each category

In [43]:
app_count_per_cat = df["Category"].value_counts()

### 35. Perform multiple aggregations (mean rating, max installs) per category

In [44]:
cat_summary = df.groupby("Category").agg({"Rating": "mean", "Installs": "max"})

In [45]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre,Rating_Group,Type_Numeric,Rating_Rank
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,Art & Design,Medium,0.0,5753.0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,Art & Design,Medium,0.0,6949.0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,Art & Design,High,0.0,588.0
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,Art & Design,High,0.0,1840.0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,Art & Design,High,0.0,3849.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,fr calculator,FAMILY,4.0,7,2.6M,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up,Education,Medium,0.0,6410.0
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,Education,High,0.0,1840.0
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,Education,High,0.0,2.0
10839,the scp foundation db fr nn5n,BOOKS AND REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,Books & Reference,High,0.0,1840.0
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,Lifestyle,High,0.0,1840.0

##  MERGE / JOIN / CONCAT

### 36. Split the dataset into multiple tables

In [61]:
apps_info=df[['App', 'Category', 'Rating', 'Reviews']]
installs_info=df[['App', 'Installs']]
pricing_info=df[['App', 'Type', 'Price']]

print(apps_info.head())
print(installs_info.head())
print(pricing_info.head())

                                                 App        Category  Rating  \
0     photo editor & candy camera & grid & scrapbook  ART AND DESIGN     4.1
1                                coloring book moana  ART AND DESIGN     3.9
2  u launcher lite – free live cool themes, hide ...  ART AND DESIGN     4.7
3                              sketch - draw & paint  ART AND DESIGN     4.5
4              pixel draw - number art coloring book  ART AND DESIGN     4.3

    Reviews
0     159.0
1     967.0
2   87510.0
3  215644.0
4     967.0
                                                 App    Installs
0     photo editor & candy camera & grid & scrapbook     10000.0
1                                coloring book moana    500000.0
2  u launcher lite – free live cool themes, hide ...   5000000.0
3                              sketch - draw & paint  50000000.0
4              pixel draw - number art coloring book    100000.0
                                                 App  Type Price
0     photo editor & candy camera & grid & scrapbook  Free     0
1                                coloring book moana  Free     0
2  u launcher lite – free live cool themes, hide ...  Free     0
3                              sketch - draw & paint  Free     0
4              pixel draw - number art coloring book  Free     0

### 37. Merge app details with installs data using a common column

In [48]:
merged_df = pd.merge(apps_info, installs_info, on="App")

### 38. Perform an inner join

In [49]:
inner_merged = pd.merge(apps_info, installs_info, on="App", how="inner")

### 39. Perform a left join and identify missing values created after the merge

In [62]:
merged_data=pd.merge(apps_info,installs_info,on='App',how='left')

missing_values=merged_data[merged_data['Installs'].isnull()]

print("Missing values:")
print(missing_values)

print("Number of missing Installs:")
print(merged_data['Installs'].isnull().sum())

Missing values:
                                           App Category  Rating  Reviews  \
10629  life made wi-fi touchscreen photo frame      1.9    19.0      NaN

       Installs
10629       NaN
Number of missing Installs:
1

### 40. Combine two DataFrames vertically to simulate adding new data

In [51]:
df_part1 = df.iloc[:5000]
df_part2 = df.iloc[5000:]
concatenated_df = pd.concat([df_part1, df_part2], axis=0)